/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs282.project.gui;

/**
 *
 * @author Jur Yel
 */
import cs282.project.core.Account;
import cs282.project.dao.AccountDAO;
import cs282.project.core.CurrentAccount;
import cs282.project.dao.CurrentAccountDAO;
import javax.swing.JOptionPane;
public class HomeUI_CreateBankAccount extends javax.swing.JDialog {

    /**
     * Creates new form HomeUI_CreateBankAccount
     */
    private AccountDAO accDAO;
    private int branchID;
    private int customerID;
    private String customerName;
    private HomeUI_ForLoans loanUI;
    private CurrentAccountDAO curAccDAO;
    
    public HomeUI_CreateBankAccount(int br,int cust,String custName,HomeUI_ForLoans ui){
        try{
            accDAO = new AccountDAO();
            curAccDAO = new CurrentAccountDAO();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(ui);
        branchID = br;
        customerID = cust;
        customerName = custName;
        jtxt_Name.setText(custName);
    }
    
    public HomeUI_CreateBankAccount(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxt_AccountID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxt_Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxt_Balance = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jpf_Pin = new javax.swing.JPasswordField();
        jCheckBox_Show = new javax.swing.JCheckBox();
        jbtn_Create = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Bank Account");

        jLabel2.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Account ID:");

        jtxt_AccountID.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_AccountID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name:");

        jtxt_Name.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_Name.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Opening Balance:");

        jtxt_Balance.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_Balance.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Account Pin:");

        jpf_Pin.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jpf_Pin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpf_Pin.setToolTipText("");

        jCheckBox_Show.setFont(new java.awt.Font("Alata", 0, 12)); // NOI18N
        jCheckBox_Show.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_Show.setText("Show Pin");
        jCheckBox_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ShowActionPerformed(evt);
            }
        });

        jbtn_Create.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_Create.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_Create.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Create.setText("Create Account");
        jbtn_Create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxt_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxt_AccountID, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpf_Pin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jCheckBox_Show))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jbtn_Create)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_AccountID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jpf_Pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_Show)
                .addGap(18, 18, 18)
                .addComponent(jbtn_Create)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ShowActionPerformed
        if(jCheckBox_Show.isSelected()){
            jpf_Pin.setEchoChar((char)0);
        }
        else{
            jpf_Pin.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox_ShowActionPerformed

    private void jbtn_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CreateActionPerformed
        try{
            String accID = jtxt_AccountID.getText().trim();
            double balance = Double.parseDouble(jtxt_Balance.getText().trim());
            String pin = jpf_Pin.getText().trim();
            
            if(accDAO.checkAccountID(accID)){
                JOptionPane.showMessageDialog(HomeUI_CreateBankAccount.this,"Account ID already exists!","Creation Error",JOptionPane.ERROR_MESSAGE);
                
                
            }
            else{
                if(balance < 300){
                    JOptionPane.showMessageDialog(HomeUI_CreateBankAccount.this,"Opening Balance should be at least P300","Creation Error",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    if(pin.length() == 6){
                        Account account = new Account(null,null,null,balance,pin);
                        account.setAccountID(accID);
                        account.setBranchID(branchID);
                        account.setCustomerID(customerID);

                        accDAO.registerAccount(account);
                        CurrentAccount current = new CurrentAccount(accID,null,balance,null);
                        curAccDAO.addCurrentAccount(current);
                        JOptionPane.showMessageDialog(HomeUI_CreateBankAccount.this,
                                "Account created successfully!\nNote: Please remember your Account ID and PIN","Creation Success",JOptionPane.INFORMATION_MESSAGE);
                        setVisible(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(HomeUI_CreateBankAccount.this,
                                "Account Pin should be 6 characters long","Creation Error",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_CreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUI_CreateBankAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUI_CreateBankAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUI_CreateBankAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUI_CreateBankAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomeUI_CreateBankAccount dialog = new HomeUI_CreateBankAccount(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox_Show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_Create;
    private javax.swing.JPasswordField jpf_Pin;
    private javax.swing.JTextField jtxt_AccountID;
    private javax.swing.JTextField jtxt_Balance;
    private javax.swing.JTextField jtxt_Name;
    // End of variables declaration//GEN-END:variables
}
