/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs282.project.gui;

/**
 *
 * @author Jur Yel
 */
import cs282.project.core.Loan;
import cs282.project.core.LoanHistory;
import cs282.project.dao.LoanDAO;
import cs282.project.dao.LoanHistoryDAO;
import cs282.project.dao.CustomerDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
public class HomeUI_ForLoans extends javax.swing.JFrame {

    /**
     * Creates new form HomeUI_ForLoans
     */
    private String customerName;
    private int branchID;
    private LoanDAO loanDAO;
    private LoanHistoryDAO loanHistDAO;
    private CustomerDAO custDAO;
    public HomeUI_ForLoans(String name,int brID) {
        try{
            loanDAO = new LoanDAO();
            loanHistDAO = new LoanHistoryDAO();
            custDAO = new CustomerDAO();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null);
        customerName = name;
        branchID = brID;
        populateGUI();
        populateTable();
//        updateLoans();
    }
    
    public HomeUI_ForLoans(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbl_Customer = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jlbl_Loaned = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbl_Balance = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlbl_LastPaid = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlbl_Amount = new javax.swing.JLabel();
        jbtn_7 = new javax.swing.JButton();
        jbtn_8 = new javax.swing.JButton();
        jbtn_9 = new javax.swing.JButton();
        jbtn_4 = new javax.swing.JButton();
        jbtn_5 = new javax.swing.JButton();
        jbtn_6 = new javax.swing.JButton();
        jbtn_3 = new javax.swing.JButton();
        jbtn_2 = new javax.swing.JButton();
        jbtn_1 = new javax.swing.JButton();
        jbtn_CA = new javax.swing.JButton();
        jbtn_0 = new javax.swing.JButton();
        jbtn_Dot = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_Loans = new javax.swing.JTable();
        jbtn_LoanAmount = new javax.swing.JButton();
        jComboBox_LoanType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jbtn_Reimburse = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jlbl_LoanNumber = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbtn_Create = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User");

        jlbl_Customer.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jlbl_Customer.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_Customer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_Customer.setText("Label");
        jlbl_Customer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jlbl_Customer, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addComponent(jlbl_Customer, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Loaned");

        jlbl_Loaned.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jlbl_Loaned.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_Loaned.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_Loaned.setText("jLabel4");
        jlbl_Loaned.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Balance");

        jlbl_Balance.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jlbl_Balance.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_Balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_Balance.setText("jLabel4");
        jlbl_Balance.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Last Paid");

        jlbl_LastPaid.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jlbl_LastPaid.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_LastPaid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_LastPaid.setText("jLabel4");
        jlbl_LastPaid.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jlbl_Loaned, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jlbl_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jlbl_LastPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbl_LastPaid))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbl_Balance))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbl_Loaned))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlbl_Amount.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jlbl_Amount.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_Amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_Amount.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbtn_7.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_7.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_7.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_7.setText("7");
        jbtn_7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_7ActionPerformed(evt);
            }
        });

        jbtn_8.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_8.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_8.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_8.setText("8");
        jbtn_8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_8ActionPerformed(evt);
            }
        });

        jbtn_9.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_9.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_9.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_9.setText("9");
        jbtn_9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_9ActionPerformed(evt);
            }
        });

        jbtn_4.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_4.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_4.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_4.setText("4");
        jbtn_4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_4ActionPerformed(evt);
            }
        });

        jbtn_5.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_5.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_5.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_5.setText("5");
        jbtn_5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_5ActionPerformed(evt);
            }
        });

        jbtn_6.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_6.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_6.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_6.setText("6");
        jbtn_6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_6ActionPerformed(evt);
            }
        });

        jbtn_3.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_3.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_3.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_3.setText("3");
        jbtn_3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_3ActionPerformed(evt);
            }
        });

        jbtn_2.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_2.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_2.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_2.setText("2");
        jbtn_2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_2ActionPerformed(evt);
            }
        });

        jbtn_1.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_1.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_1.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_1.setText("1");
        jbtn_1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_1ActionPerformed(evt);
            }
        });

        jbtn_CA.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_CA.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_CA.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_CA.setText("CA");
        jbtn_CA.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_CA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_CA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CAActionPerformed(evt);
            }
        });

        jbtn_0.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_0.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_0.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_0.setText("0");
        jbtn_0.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_0ActionPerformed(evt);
            }
        });

        jbtn_Dot.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_Dot.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_Dot.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Dot.setText(".");
        jbtn_Dot.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_Dot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_DotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbtn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbtn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbtn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbtn_CA, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlbl_Amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbl_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_CA, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtbl_Loans.setFont(new java.awt.Font("Alata", 0, 12)); // NOI18N
        jtbl_Loans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbl_Loans);

        jbtn_LoanAmount.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_LoanAmount.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_LoanAmount.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_LoanAmount.setText("Loan Amount");
        jbtn_LoanAmount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_LoanAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_LoanAmountActionPerformed(evt);
            }
        });

        jComboBox_LoanType.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jComboBox_LoanType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Short-Term", "Long-Term" }));

        jLabel4.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Loan Type:");

        jbtn_Reimburse.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_Reimburse.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_Reimburse.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Reimburse.setText("Reimburse Credit");
        jbtn_Reimburse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Reimburse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ReimburseActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Loan Number:");

        jlbl_LoanNumber.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jlbl_LoanNumber.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_LoanNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_LoanNumber.setText("jLabel7");
        jlbl_LoanNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtn_Create.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_Create.setFont(new java.awt.Font("Alata", 0, 12)); // NOI18N
        jbtn_Create.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Create.setText("Create Bank Account");
        jbtn_Create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn_Create, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jbtn_LoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addComponent(jbtn_Reimburse, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_LoanType, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlbl_LoanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_Create)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_LoanType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jlbl_LoanNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn_LoanAmount)
                            .addComponent(jbtn_Reimburse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_7ActionPerformed
        setAmount("7");
    }//GEN-LAST:event_jbtn_7ActionPerformed

    private void jbtn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_8ActionPerformed
        setAmount("8");
    }//GEN-LAST:event_jbtn_8ActionPerformed

    private void jbtn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_9ActionPerformed
        setAmount("9");
    }//GEN-LAST:event_jbtn_9ActionPerformed

    private void jbtn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_4ActionPerformed
        setAmount("4");
    }//GEN-LAST:event_jbtn_4ActionPerformed

    private void jbtn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_5ActionPerformed
        setAmount("5");
    }//GEN-LAST:event_jbtn_5ActionPerformed

    private void jbtn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_6ActionPerformed
        setAmount("6");
    }//GEN-LAST:event_jbtn_6ActionPerformed

    private void jbtn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_3ActionPerformed
        setAmount("3");
    }//GEN-LAST:event_jbtn_3ActionPerformed

    private void jbtn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_2ActionPerformed
        setAmount("2");
    }//GEN-LAST:event_jbtn_2ActionPerformed

    private void jbtn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_1ActionPerformed
        setAmount("1");
    }//GEN-LAST:event_jbtn_1ActionPerformed

    private void jbtn_CAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CAActionPerformed
        jlbl_Amount.setText("");
    }//GEN-LAST:event_jbtn_CAActionPerformed

    private void jbtn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_0ActionPerformed
        setAmount("0");
    }//GEN-LAST:event_jbtn_0ActionPerformed

    private void jbtn_DotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_DotActionPerformed
        setAmount(".");
    }//GEN-LAST:event_jbtn_DotActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HomeUI_Login login = new HomeUI_Login();
        setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtn_LoanAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_LoanAmountActionPerformed
        try{
            int customerID = custDAO.getCustomerID(customerName);
            double amount = 0;
            String type = jComboBox_LoanType.getSelectedItem().toString();
            
            if(jlbl_Amount.getText().isEmpty()){
                JOptionPane.showMessageDialog(HomeUI_ForLoans.this,"Please provide amount","Loan Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                amount = Double.parseDouble(jlbl_Amount.getText().trim());
                    if(loanDAO.checkUserHasLoan(customerID)){
                    ArrayList<Loan> loanDetails = loanDAO.getUserLoanDetails(customerID);

                    JOptionPane.showMessageDialog(HomeUI_ForLoans.this,
                            "You already made a loan; \n\n"
                          + "\tLoan No. : " + loanDetails.get(0).getLoanNumber() + "\n"
                          + "\tLoan Type : " + loanDetails.get(0).getLoanType() + "\n"
                          + "\tAmount : " + loanDetails.get(0).getAmount() + "\n"
                          + "\tBalance :" + loanDetails.get(0).getBalance() + "\n"
                          + "\tLoan Date : " + loanDetails.get(0).getStrLoanDate() + "\n\n"
                          + "Unable to make a loan on top of a previous unpaid loan.","Loan Error",JOptionPane.ERROR_MESSAGE);

                }
                else{
                    Loan loan = new Loan(0,null,null,null,amount,amount,type,null);
                    loan.setBranchID(branchID);
                    loan.setCustomerID(customerID);

    //                loanDAO.addLoan(loan);
    //                int loan_no = loanDAO.getLoanID(customerID);
    //                LoanHistory loanHistory = new LoanHistory(null,null,"Loaned",amount,null);
    //                loanHistory.setCustomerID(customerID);
    //                loanHistory.setLoanNo(loan_no);
    //                loanHistory.setLoanType(type);
    //                
    //                loanHistDAO.recordAction(loanHistory);
    //                
    //                populateTable();
    //                
    //                jlbl_Loaned.setText(String.valueOf(amount));
    //                jlbl_Balance.setText(String.valueOf(amount));
    //                jlbl_LastPaid.setText("No Record");
    //                jlbl_LoanNumber.setText(String.valueOf(loan_no));

                      HomeUI_DateChooser dateUI = new HomeUI_DateChooser(branchID,customerID,loan,loanDAO,HomeUI_ForLoans.this);
                      dateUI.setVisible(true);

                }
            }
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_LoanAmountActionPerformed

    private void jbtn_ReimburseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ReimburseActionPerformed
        try{
            double amount = 0;
            int loan_no = 0;
            double balance = Double.parseDouble(jlbl_Balance.getText());
            double loaned = Double.parseDouble(jlbl_Loaned.getText());
            ArrayList<String> paytimes = new ArrayList<>();
            
            int customerID = custDAO.getCustomerID(customerName);
            ArrayList<String> loan_types = new ArrayList<>();
            
            if(jlbl_Amount.getText().isEmpty()){
                JOptionPane.showMessageDialog(HomeUI_ForLoans.this,"Please provide amount","Reimburse Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                amount = Double.parseDouble(jlbl_Amount.getText().trim());
                if(jlbl_LoanNumber.getText().equals("No Loans")){
                    JOptionPane.showMessageDialog(HomeUI_ForLoans.this,"Cannot reimburse without any loans","Reimburse Error",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    loan_no = Integer.parseInt(jlbl_LoanNumber.getText());
                    loan_types = loanHistDAO.getLoanType(loan_no);
                    paytimes = loanHistDAO.getLastPaidByLoanNo(loan_no);
                    if(loanDAO.checkIfLoanPaid(loan_no)){
                        JOptionPane.showMessageDialog(HomeUI_ForLoans.this,"Loan is already paid last " + paytimes.get(0),"Payment Error",JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        if(amount == loaned){
                            loanDAO.fullLoanPayment(loan_no);

                            LoanHistory loanHist = new LoanHistory(null,null,"Full Payment",amount,null);
                            loanHist.setLoanNo(loan_no);
                            loanHist.setCustomerID(customerID);
                            loanHist.setLoanType(loan_types.get(0));

                            loanHistDAO.recordAction(loanHist);
                            this.refreshLoansHistory();
                            this.refreshLoansGUI(0.0,0.0,paytimes.get(0),-1);
                        }
                        else if(amount <= balance){
                            loanDAO.reimburseLoan(loan_no, (balance - amount));

                            LoanHistory loanHist = new LoanHistory(null,null,"Paid Portion",amount,null);
                            loanHist.setCustomerID(customerID);
                            loanHist.setLoanNo(loan_no);
                            loanHist.setLoanType(loan_types.get(0));

                            loanHistDAO.recordAction(loanHist);
                            
                            this.refreshLoansHistory();
                            
                            if((balance - amount) == 0.0){
                                JOptionPane.showMessageDialog(HomeUI_ForLoans.this,"Loan fully paid!","Reimbursed Credit",JOptionPane.ERROR_MESSAGE);
                                loanDAO.fullLoanPayment(loan_no);
                                this.refreshLoansGUI(0.0,(balance - amount),"No Record", -1);
                            }
                            else{
                                this.refreshLoansGUI(loaned,(balance - amount),paytimes.get(0),loan_no);
                            }
                            
                            
                            
                            
                        }
                    }
                }
                
                reset();
            }
            
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_ReimburseActionPerformed

    private void jbtn_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CreateActionPerformed
        try{
            int custID = custDAO.getCustomerID(customerName);
            HomeUI_CreateBankAccount createUI = new HomeUI_CreateBankAccount(branchID,custID,customerName,HomeUI_ForLoans.this);
            createUI.setVisible(true);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        
    }//GEN-LAST:event_jbtn_CreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUI_ForLoans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUI_ForLoans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUI_ForLoans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUI_ForLoans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUI_ForLoans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_LoanType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_0;
    private javax.swing.JButton jbtn_1;
    private javax.swing.JButton jbtn_2;
    private javax.swing.JButton jbtn_3;
    private javax.swing.JButton jbtn_4;
    private javax.swing.JButton jbtn_5;
    private javax.swing.JButton jbtn_6;
    private javax.swing.JButton jbtn_7;
    private javax.swing.JButton jbtn_8;
    private javax.swing.JButton jbtn_9;
    private javax.swing.JButton jbtn_CA;
    private javax.swing.JButton jbtn_Create;
    private javax.swing.JButton jbtn_Dot;
    private javax.swing.JButton jbtn_LoanAmount;
    private javax.swing.JButton jbtn_Reimburse;
    private javax.swing.JLabel jlbl_Amount;
    private javax.swing.JLabel jlbl_Balance;
    private javax.swing.JLabel jlbl_Customer;
    private javax.swing.JLabel jlbl_LastPaid;
    private javax.swing.JLabel jlbl_LoanNumber;
    private javax.swing.JLabel jlbl_Loaned;
    private javax.swing.JTable jtbl_Loans;
    // End of variables declaration//GEN-END:variables
   
    public void refreshLoansHistory(){
        try{
            int customerID = custDAO.getCustomerID(customerName);
            ArrayList<LoanHistory> list = loanHistDAO.getUserLoans(customerID);
            UserLoanHistoryTableModel model = new UserLoanHistoryTableModel(list);
            jtbl_Loans.setModel(model);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
    
    public void refreshLoansGUI(double loaned,double amount,String paid, int loan_no){
        jlbl_Loaned.setText(String.valueOf(loaned));
                jlbl_Balance.setText(String.valueOf(amount));
                jlbl_LastPaid.setText(paid);
                if(loan_no == -1){
                    jlbl_LoanNumber.setText("No Loans");
                }
                else{
                    jlbl_LoanNumber.setText(String.valueOf(loan_no));
                }
                
    }
    
    private void populateGUI(){
        try{
            int customerID = custDAO.getCustomerID(customerName);
            int loan_no = loanDAO.getLoanID(customerID);
            double amount = loanDAO.getLoanAmount(loan_no);
            double bal = loanDAO.getLoanBalance(loan_no);
            
            ArrayList<String> paytimes = loanHistDAO.getLastPaidByLoanNo(loan_no);
            
            jlbl_Customer.setText(customerName);
            jlbl_Loaned.setText(String.valueOf(amount));
            jlbl_Balance.setText(String.valueOf(bal));
            if(paytimes.size() > 0){
                jlbl_LastPaid.setText(paytimes.get(0));
            }
            else{
                jlbl_LastPaid.setText("No Record");
            }
            
            if(loan_no == 0){
                jlbl_LoanNumber.setText("No Loans");
            }
            else{
                jlbl_LoanNumber.setText(String.valueOf(loan_no));
            }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
    
    private void populateTable(){
        try{
            int customerID = custDAO.getCustomerID(customerName);
            ArrayList<LoanHistory> list = loanHistDAO.getUserLoans(customerID);
            UserLoanHistoryTableModel model = new UserLoanHistoryTableModel(list);
            jtbl_Loans.setModel(model);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
    
    public void reset(){
        jlbl_Amount.setText("");
    }
    
    private void updateLoans(){
        try{
            loanDAO.longTermInterest();
            loanDAO.shortTermInterest();
            
            populateGUI();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
    
    private void setAmount(String str){
        if(jlbl_Amount.getText().trim().length() < 11){
            jlbl_Amount.setText(jlbl_Amount.getText() + str);
        }
    }
}
