/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs282.project.gui;

/**
 *
 * @author Jur Yel
 */
import cs282.project.core.Loan;
import cs282.project.core.LoanHistory;
import cs282.project.dao.LoanDAO;
import cs282.project.dao.LoanHistoryDAO;
import java.util.Date;
import javax.swing.JOptionPane;

public class HomeUI_DateChooser extends javax.swing.JDialog {

    /**
     * Creates new form HomeUI_DateChooser
     */
    private int branchID;
    private int customerID;
    private Loan loan;
    private LoanDAO loanDAO;
    private LoanHistoryDAO loanHistDAO;
    private HomeUI_ForLoans loanUI;
    
    public HomeUI_DateChooser(int branch,int cust,Loan theLoan,LoanDAO dao,HomeUI_ForLoans UI){
        try{
            loanHistDAO = new LoanHistoryDAO();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(UI);
        branchID = branch;
        customerID = cust;
        loan = theLoan;
        loanDAO = dao;
        loanUI = UI;
        populateGUI();
    }
    
    public HomeUI_DateChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_Title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dcc_Date = new datechooser.beans.DateChooserCombo();
        jbtn_Loan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jlbl_Title.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jlbl_Title.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_Title.setText("Short-Term Loan");

        jLabel2.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("When are you going");

        jLabel3.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" to pay the loan");

        dcc_Date.setCalendarPreferredSize(new java.awt.Dimension(350, 250));
        dcc_Date.setFieldFont(new java.awt.Font("Alata", java.awt.Font.PLAIN, 14));

        jbtn_Loan.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_Loan.setText("Loan Amount");
        jbtn_Loan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_LoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcc_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(14, 14, 14)))
                        .addComponent(jlbl_Title)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_Loan)
                .addGap(97, 97, 97))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlbl_Title)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(dcc_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jbtn_Loan)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_LoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_LoanActionPerformed
        try{
            Date curdate = new Date();
            Date loan_date = dcc_Date.getSelectedDate().getTime();
            int curMS = (int)curdate.getTime();
            int loanMS = (int)loan_date.getTime();
            
            
            if(loan_date.getTime() < curdate.getTime()){
                JOptionPane.showMessageDialog(HomeUI_DateChooser.this,"Please pick a viable date","Loan Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                loanDAO.addLoan(loan);
                        int loan_no = loanDAO.getLoanID(customerID);

                        LoanHistory loanHistory = new LoanHistory(null,null,"Loaned",loan.getAmount(),null);
                        loanHistory.setCustomerID(customerID);
                        loanHistory.setLoanNo(loan_no);
                        loanHistory.setLoanType(loan.getLoanType());

                        loanHistDAO.recordAction(loanHistory);

                        loanUI.reset();
                        loanUI.refreshLoansHistory();   
                        loanUI.refreshLoansGUI(loan.getAmount(),loan.getAmount(),"No Record", loan_no);
                        setVisible(false);
                        loanUI.setVisible(true);
                
            }
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_LoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUI_DateChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUI_DateChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUI_DateChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUI_DateChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomeUI_DateChooser dialog = new HomeUI_DateChooser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dcc_Date;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_Loan;
    private javax.swing.JLabel jlbl_Title;
    // End of variables declaration//GEN-END:variables

    private void populateGUI(){
        if(loan.getLoanType().equals("Short-Term")){
            jlbl_Title.setText("Short-Term Loan");
        }
        else if(loan.getLoanType().equals("Long-Term")){
            jlbl_Title.setText("Long-Term Loan");
        }
    }
    
    private int convertMSToDays(int ms){
        int days = (int)Math.ceil(ms/(1000*60*60*24))+1;
        return days;
    }
}
