/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs282.project.gui;

/**
 *
 * @author Jur Yel
 */
import java.util.ArrayList;
import cs282.project.core.Account;
import cs282.project.core.CurrentAccount;
import cs282.project.core.SavingsAccount;
import cs282.project.core.TransactionHistory;
import cs282.project.dao.AccountDAO;
import cs282.project.dao.CurrentAccountDAO;
import cs282.project.dao.SavingsAccountDAO;
import cs282.project.dao.TransactionHistoryDAO;
import cs282.project.dao.UserLoginHistoryDAO;
import javax.swing.JOptionPane;

public class HomeUI_ForTransactions extends javax.swing.JFrame {

    /**
     * Creates new form HomeUI_ForTransactions
     */
    private String accountID;
    private AccountDAO accDAO;
    private CurrentAccountDAO curAccDAO;
    private SavingsAccountDAO savAccDAO;
    private TransactionHistoryDAO transDAO;
    private UserLoginHistoryDAO userLogDAO;
    
    public HomeUI_ForTransactions(String id) {
        try{
            accDAO = new AccountDAO();
            curAccDAO = new CurrentAccountDAO();
            savAccDAO = new SavingsAccountDAO();
            transDAO = new TransactionHistoryDAO();
            userLogDAO = new UserLoginHistoryDAO();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null);
        accountID = id;
        populateGUI();
        populateTable();
//        updateSavings();
    }
    
    public HomeUI_ForTransactions(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbl_User = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jlbl_Balance = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbl_Savings = new javax.swing.JLabel();
        jlbl_LastLogin = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlbl_Amount = new javax.swing.JLabel();
        jbtn_7 = new javax.swing.JButton();
        jbtn_8 = new javax.swing.JButton();
        jbtn_9 = new javax.swing.JButton();
        jbtn_4 = new javax.swing.JButton();
        jbtn_5 = new javax.swing.JButton();
        jbtn_6 = new javax.swing.JButton();
        jbtn_3 = new javax.swing.JButton();
        jbtn_2 = new javax.swing.JButton();
        jbtn_1 = new javax.swing.JButton();
        jbtn_CA = new javax.swing.JButton();
        jbtn_0 = new javax.swing.JButton();
        jbtn_Dot = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_Transactions = new javax.swing.JTable();
        jbtn_DepositCurrent = new javax.swing.JButton();
        jbtn_DepositSavings = new javax.swing.JButton();
        jbtn_WithdrawCurrent = new javax.swing.JButton();
        jbtn_WithdrawSavings = new javax.swing.JButton();
        jbtn_WithdrawAll = new javax.swing.JButton();
        jbtn_Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User");

        jlbl_User.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jlbl_User.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_User.setText("Label");
        jlbl_User.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jlbl_User, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jlbl_User, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Balance");

        jlbl_Balance.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jlbl_Balance.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_Balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_Balance.setText("0.0");
        jlbl_Balance.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Savings");

        jlbl_Savings.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jlbl_Savings.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_Savings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_Savings.setText("0.0");
        jlbl_Savings.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlbl_LastLogin.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jlbl_LastLogin.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_LastLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_LastLogin.setText("Label");
        jlbl_LastLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Last Login");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbl_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbl_Savings, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbl_LastLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbl_Savings)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_LastLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbl_Balance))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlbl_Amount.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jlbl_Amount.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_Amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_Amount.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbtn_7.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_7.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_7.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_7.setText("7");
        jbtn_7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_7ActionPerformed(evt);
            }
        });

        jbtn_8.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_8.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_8.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_8.setText("8");
        jbtn_8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_8ActionPerformed(evt);
            }
        });

        jbtn_9.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_9.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_9.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_9.setText("9");
        jbtn_9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_9ActionPerformed(evt);
            }
        });

        jbtn_4.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_4.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_4.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_4.setText("4");
        jbtn_4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_4ActionPerformed(evt);
            }
        });

        jbtn_5.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_5.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_5.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_5.setText("5");
        jbtn_5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_5ActionPerformed(evt);
            }
        });

        jbtn_6.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_6.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_6.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_6.setText("6");
        jbtn_6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_6ActionPerformed(evt);
            }
        });

        jbtn_3.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_3.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_3.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_3.setText("3");
        jbtn_3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_3ActionPerformed(evt);
            }
        });

        jbtn_2.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_2.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_2.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_2.setText("2");
        jbtn_2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_2ActionPerformed(evt);
            }
        });

        jbtn_1.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_1.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_1.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_1.setText("1");
        jbtn_1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_1ActionPerformed(evt);
            }
        });

        jbtn_CA.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_CA.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_CA.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_CA.setText("CA");
        jbtn_CA.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_CA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_CA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CAActionPerformed(evt);
            }
        });

        jbtn_0.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_0.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_0.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_0.setText("0");
        jbtn_0.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_0ActionPerformed(evt);
            }
        });

        jbtn_Dot.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_Dot.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jbtn_Dot.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Dot.setText(".");
        jbtn_Dot.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtn_Dot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_DotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbtn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbtn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbtn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbtn_CA, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlbl_Amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbl_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_CA, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtbl_Transactions.setFont(new java.awt.Font("Alata", 0, 12)); // NOI18N
        jtbl_Transactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbl_Transactions);

        jbtn_DepositCurrent.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_DepositCurrent.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_DepositCurrent.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_DepositCurrent.setText("Deposit Current");
        jbtn_DepositCurrent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_DepositCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_DepositCurrentActionPerformed(evt);
            }
        });

        jbtn_DepositSavings.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_DepositSavings.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_DepositSavings.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_DepositSavings.setText("Deposit Savings");
        jbtn_DepositSavings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_DepositSavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_DepositSavingsActionPerformed(evt);
            }
        });

        jbtn_WithdrawCurrent.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_WithdrawCurrent.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_WithdrawCurrent.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_WithdrawCurrent.setText("Withdraw Current");
        jbtn_WithdrawCurrent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_WithdrawCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_WithdrawCurrentActionPerformed(evt);
            }
        });

        jbtn_WithdrawSavings.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_WithdrawSavings.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_WithdrawSavings.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_WithdrawSavings.setText("Withdraw Savings");
        jbtn_WithdrawSavings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_WithdrawSavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_WithdrawSavingsActionPerformed(evt);
            }
        });

        jbtn_WithdrawAll.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_WithdrawAll.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_WithdrawAll.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_WithdrawAll.setText("Withdraw All Current Balance");
        jbtn_WithdrawAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_WithdrawAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_WithdrawAllActionPerformed(evt);
            }
        });

        jbtn_Logout.setBackground(new java.awt.Color(0, 0, 0));
        jbtn_Logout.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_Logout.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Logout.setText("Logout");
        jbtn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbtn_WithdrawCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(jbtn_WithdrawSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbtn_DepositCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(jbtn_DepositSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jbtn_WithdrawAll, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_Logout))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Logout))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_DepositCurrent)
                            .addComponent(jbtn_DepositSavings))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_WithdrawCurrent)
                            .addComponent(jbtn_WithdrawSavings))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_WithdrawAll)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_DepositSavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_DepositSavingsActionPerformed
        try{
            double amount = 0;
            double savings = Double.parseDouble(jlbl_Savings.getText());
            double balance = Double.parseDouble(jlbl_Balance.getText());
            double updateSv = 0;
            double updateBal = 0;
            
            if(jlbl_Amount.getText().isEmpty()){
                JOptionPane.showMessageDialog(HomeUI_ForTransactions.this,"Please provide amount","Deposit Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                amount = Double.parseDouble(jlbl_Amount.getText().trim());
                
                if(amount <= balance){
                    updateSv = savings + amount;
                    updateBal = balance - amount;

                    accDAO.withdrawAmount(accountID, updateBal);
                    curAccDAO.withdrawAmount(accountID,updateBal);
                    
                    if(savAccDAO.checkSavingsAccountID(accountID)){
                        savAccDAO.depositSavings(accountID, updateSv);
                    }
                    else{
                        SavingsAccount sav = new SavingsAccount(accountID,null,updateSv,null);
                        savAccDAO.addSavingsAccount(sav);
                    }
                    
                    jlbl_Savings.setText(String.valueOf(updateSv));
                    jlbl_Balance.setText(String.valueOf(updateBal));

                    TransactionHistory trans = new TransactionHistory(accountID,"Deposit","Savings",amount,null);
                    transDAO.recordTransaction(trans);
                    populateTable();
                    jlbl_Amount.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(HomeUI_ForTransactions.this,"Amount exceeds current balance","Transaction Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_DepositSavingsActionPerformed

    private void jbtn_WithdrawSavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_WithdrawSavingsActionPerformed
        try{
            double amount = 0;
            double savings = Double.parseDouble(jlbl_Savings.getText());
            double updateSv = 0;
            
            if(jlbl_Amount.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(HomeUI_ForTransactions.this,"Please provide amount","Withdraw Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                amount = Double.parseDouble(jlbl_Amount.getText().trim());
                if(amount <= savings){
                    updateSv = savings - amount;

                    savAccDAO.withdrawSavings(accountID, updateSv);
                    jlbl_Savings.setText(String.valueOf(updateSv));

                    TransactionHistory trans = new TransactionHistory(accountID,"Withdraw","Savings",amount,null);
                    transDAO.recordTransaction(trans);
                    populateTable();
                    jlbl_Amount.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(HomeUI_ForTransactions.this,"Amount exceeds current savings","Transaction Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_WithdrawSavingsActionPerformed

    private void jbtn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_7ActionPerformed
        setAmount("7");
    }//GEN-LAST:event_jbtn_7ActionPerformed

    private void jbtn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_8ActionPerformed
        setAmount("8");
    }//GEN-LAST:event_jbtn_8ActionPerformed

    private void jbtn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_9ActionPerformed
        setAmount("9");
    }//GEN-LAST:event_jbtn_9ActionPerformed

    private void jbtn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_4ActionPerformed
        setAmount("4");
    }//GEN-LAST:event_jbtn_4ActionPerformed

    private void jbtn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_5ActionPerformed
        setAmount("5");
    }//GEN-LAST:event_jbtn_5ActionPerformed

    private void jbtn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_6ActionPerformed
        setAmount("6");
    }//GEN-LAST:event_jbtn_6ActionPerformed

    private void jbtn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_3ActionPerformed
        setAmount("3");
    }//GEN-LAST:event_jbtn_3ActionPerformed

    private void jbtn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_2ActionPerformed
        setAmount("2");
    }//GEN-LAST:event_jbtn_2ActionPerformed

    private void jbtn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_1ActionPerformed
        setAmount("1");
    }//GEN-LAST:event_jbtn_1ActionPerformed

    private void jbtn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_0ActionPerformed
        setAmount("0");
    }//GEN-LAST:event_jbtn_0ActionPerformed

    private void jbtn_CAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CAActionPerformed
        jlbl_Amount.setText("");
    }//GEN-LAST:event_jbtn_CAActionPerformed

    private void jbtn_DotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_DotActionPerformed
        setAmount(".");
    }//GEN-LAST:event_jbtn_DotActionPerformed

    private void jbtn_DepositCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_DepositCurrentActionPerformed
        try{
            double amount = 0;
            double balance = Double.parseDouble(jlbl_Balance.getText());
            double update = 0;
            
            if(jlbl_Amount.getText().isEmpty()){
                JOptionPane.showMessageDialog(HomeUI_ForTransactions.this,"Please provide amount","Deposit Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                amount = Double.parseDouble(jlbl_Amount.getText());
                update = balance + amount;
                accDAO.depositCurrentAmount(accountID, update);
                curAccDAO.depositCurrentAmount(accountID, update);
                jlbl_Balance.setText(String.valueOf(update));

                /* Record Transaction */

                TransactionHistory trans = new TransactionHistory(accountID,"Deposit","Current",amount,null);
                transDAO.recordTransaction(trans);

                populateTable();
                jlbl_Amount.setText("");
                
            }
            
            
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_DepositCurrentActionPerformed

    private void jbtn_WithdrawCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_WithdrawCurrentActionPerformed
        try{
            double amount = 0;
            double balance = Double.parseDouble(jlbl_Balance.getText());
            double update = 0;
            
            if(jlbl_Amount.getText().isEmpty()){
                JOptionPane.showMessageDialog(HomeUI_ForTransactions.this,"Please provide amount","Withdraw Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                amount = Double.parseDouble(jlbl_Amount.getText());
                if(amount < balance){
                    update = balance - amount;
                    accDAO.withdrawAmount(accountID, update);
                    curAccDAO.withdrawAmount(accountID, update);

                    jlbl_Balance.setText(String.valueOf(update));

                    TransactionHistory trans = new TransactionHistory(accountID,"Withdraw","Current",amount,null);
                    transDAO.recordTransaction(trans);
                    populateTable();
                    jlbl_Amount.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(HomeUI_ForTransactions.this,"Amount exceeds current balance","Transaction Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_WithdrawCurrentActionPerformed

    private void jbtn_WithdrawAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_WithdrawAllActionPerformed
        try{
            double balance = Double.parseDouble(jlbl_Balance.getText());
            double update = 0;
            
            if((JOptionPane.showConfirmDialog(HomeUI_ForTransactions.this,"Withdraw all current balance?","Confirm Withdrawal",
                    JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE)) == JOptionPane.OK_OPTION){
                accDAO.withdrawAmount(accountID, update);
                curAccDAO.withdrawAmount(accountID, update);
                jlbl_Balance.setText(String.valueOf(update));
                
                TransactionHistory trans = new TransactionHistory(accountID,"Withdraw All","Current",balance,null);
                transDAO.recordTransaction(trans);
                populateTable();
                jlbl_Amount.setText("");
            }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_WithdrawAllActionPerformed

    private void jbtn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_LogoutActionPerformed
        HomeUI_Login login = new HomeUI_Login();
        setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jbtn_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUI_ForTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUI_ForTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUI_ForTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUI_ForTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUI_ForTransactions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_0;
    private javax.swing.JButton jbtn_1;
    private javax.swing.JButton jbtn_2;
    private javax.swing.JButton jbtn_3;
    private javax.swing.JButton jbtn_4;
    private javax.swing.JButton jbtn_5;
    private javax.swing.JButton jbtn_6;
    private javax.swing.JButton jbtn_7;
    private javax.swing.JButton jbtn_8;
    private javax.swing.JButton jbtn_9;
    private javax.swing.JButton jbtn_CA;
    private javax.swing.JButton jbtn_DepositCurrent;
    private javax.swing.JButton jbtn_DepositSavings;
    private javax.swing.JButton jbtn_Dot;
    private javax.swing.JButton jbtn_Logout;
    private javax.swing.JButton jbtn_WithdrawAll;
    private javax.swing.JButton jbtn_WithdrawCurrent;
    private javax.swing.JButton jbtn_WithdrawSavings;
    private javax.swing.JLabel jlbl_Amount;
    private javax.swing.JLabel jlbl_Balance;
    private javax.swing.JLabel jlbl_LastLogin;
    private javax.swing.JLabel jlbl_Savings;
    private javax.swing.JLabel jlbl_User;
    private javax.swing.JTable jtbl_Transactions;
    // End of variables declaration//GEN-END:variables

    private void populateTable(){
        try{
            ArrayList<TransactionHistory> list = transDAO.getUserTransactions(accountID);
            TransactionHistoryTableModel model = new TransactionHistoryTableModel(list);
            jtbl_Transactions.setModel(model);
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        
    }
    
    private void populateGUI(){
        try{
            jlbl_User.setText(accountID);
            
            double curBalance = curAccDAO.getAccountBalance(accountID);
            double savings = savAccDAO.getSavings(accountID);
            ArrayList<String> loginTimes = userLogDAO.getLastLogin(accountID);
            
            jlbl_Balance.setText(String.valueOf(curBalance));
            jlbl_Savings.setText(String.valueOf(savings));
            if(loginTimes.size() > 1){
                jlbl_LastLogin.setText(loginTimes.get(1));
            }
            else{
                jlbl_LastLogin.setText("First Login");
            }
             /* Figure out how to get recent login */
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
    
    private void updateSavings(){
        try{
            savAccDAO.gainInterest();
            
            populateGUI();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
    
    private void setAmount(String str){
        if(jlbl_Amount.getText().trim().length() < 11){
            jlbl_Amount.setText(jlbl_Amount.getText() + str);
        }
    }
}
