/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs282.project.gui;

/**
 *
 * @author Jur Yel
 */
import java.util.ArrayList;
import cs282.project.core.Branch;
import cs282.project.core.Customer;
import cs282.project.core.Employee;
import cs282.project.dao.CustomerDAO;
import cs282.project.dao.EmployeeDAO;
import cs282.project.dao.BranchDAO;
import javax.swing.JOptionPane;
public class HomeUI_Register extends javax.swing.JFrame {

    /**
     * Creates new form HomeUI_Register
     */
    private CustomerDAO custDAO;
    private EmployeeDAO empDAO;
    private BranchDAO branchDAO;
    public HomeUI_Register() {
        try{
            custDAO = new CustomerDAO();
            empDAO = new EmployeeDAO();
            branchDAO = new BranchDAO();
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
        initComponents();
        setLocationRelativeTo(null);
        populateGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_CustFirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxt_CustLastName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxt_CustAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxt_CustContactNumber = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jtxt_EmployeeID = new javax.swing.JTextField();
        jComboBox_Branch = new javax.swing.JComboBox<>();
        jtxt_EmpFirstName = new javax.swing.JTextField();
        jtxt_EmpLastName = new javax.swing.JTextField();
        jpf_Password = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jbtn_Register = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_Branch1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SYSTEM");
        jLabel3.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BANK");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MANAGEMENT");
        jLabel2.setToolTipText("");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel5.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First Name:");

        jtxt_CustFirstName.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_CustFirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last Name:");

        jtxt_CustLastName.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_CustLastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address:");

        jtxt_CustAddress.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_CustAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact Number:");

        jtxt_CustContactNumber.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_CustContactNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_CustLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_CustFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxt_CustContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxt_CustAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtxt_CustFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtxt_CustLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_CustContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxt_CustAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        jtxt_EmployeeID.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_EmployeeID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_EmployeeID.setText("Employee ID");
        jtxt_EmployeeID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_EmployeeIDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_EmployeeIDMouseExited(evt);
            }
        });

        jComboBox_Branch.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jComboBox_Branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pick a Branch" }));

        jtxt_EmpFirstName.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_EmpFirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_EmpFirstName.setText("First Name");
        jtxt_EmpFirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_EmpFirstNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_EmpFirstNameMouseExited(evt);
            }
        });

        jtxt_EmpLastName.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jtxt_EmpLastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_EmpLastName.setText("Last Name");
        jtxt_EmpLastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxt_EmpLastNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxt_EmpLastNameMouseExited(evt);
            }
        });

        jpf_Password.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jpf_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpf_Password.setText("Password");
        jpf_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpf_PasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpf_PasswordMouseExited(evt);
            }
        });
        jpf_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpf_PasswordKeyTyped(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Alata", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jtxt_EmpFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_EmpLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jtxt_EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_Branch, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jpf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Branch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_EmpFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_EmpLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jpf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCheckBox1))))
        );

        jTabbedPane1.addTab("Employee", jPanel3);

        jLabel4.setFont(new java.awt.Font("Alata", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REGISTER");

        jbtn_Register.setBackground(new java.awt.Color(204, 255, 255));
        jbtn_Register.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jbtn_Register.setText("Register");
        jbtn_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_RegisterActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Alata", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 255));
        jLabel9.setText("Login Account");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Alata", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Already have an account?");

        jComboBox_Branch1.setFont(new java.awt.Font("Alata", 0, 14)); // NOI18N
        jComboBox_Branch1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pick a Branch" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(78, 78, 78))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(187, 187, 187)
                                    .addComponent(jLabel4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(172, 172, 172)
                                    .addComponent(jbtn_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(160, 160, 160))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox_Branch1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox_Branch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_Register)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_RegisterActionPerformed
        try{
            String branchmain = jComboBox_Branch1.getSelectedItem().toString();
            String custFirst = jtxt_CustFirstName.getText().trim();
            String custLast = jtxt_CustLastName.getText().trim();
            String contact = jtxt_CustContactNumber.getText().trim();
            String address = jtxt_CustAddress.getText().trim();
            
            String employeeID = jtxt_EmployeeID.getText().trim();
            String branch = jComboBox_Branch.getSelectedItem().toString();
            int branchID = branchDAO.getBranchByCity(branch);
            String empFirst = jtxt_EmpFirstName.getText().trim();
            String empLast = jtxt_EmpLastName.getText().trim();
            String empPass = jpf_Password.getText().trim();
            
            if(branchmain.equals("Pick a Branch")){
                JOptionPane.showMessageDialog(HomeUI_Register.this,"Please pick what branch the bank is.","Register Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(!(custFirst.isEmpty()) && !(custLast.isEmpty())){
                    if(custDAO.checkIfCustomerExists(String.format("%s %s",custFirst,custLast))){
                        /* Set Bank UI for Customers with Accounts visible */
                        int branchmainID = branchDAO.getBranchIDByCity(branchmain);
                        HomeUI_ForLoans loans = new HomeUI_ForLoans(String.format("%s %s",custFirst,custLast),branchmainID);
                        setVisible(false);
                        loans.setVisible(true);
                    }
                    else{
                        Customer customer = new Customer(custFirst,custLast,address,contact);
                        custDAO.addCustomer(customer);

                        /* Set Bank UI for Customers visible */
                        
                        int branchmainID = branchDAO.getBranchIDByCity(branchmain);
                        HomeUI_ForLoans loans = new HomeUI_ForLoans(String.format("%s %s",custFirst,custLast),branchmainID);
                        setVisible(false);
                        loans.setVisible(true);
                    }
                }
                if(!(employeeID.equals("Employee ID")) && !(empPass.equals("Password"))){
                    if(empDAO.checkEmployeeID(employeeID)){
                        JOptionPane.showMessageDialog(HomeUI_Register.this,"Employee ID already exists!","Register Error",JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        Employee employee = new Employee(employeeID,branch,empFirst,empLast);
                        employee.setBranchID(branchID);
                        employee.setPassword(empPass);

                        empDAO.defRegisterEmployee(employee);

                        HomeUI_Login loginUI = new HomeUI_Login();
                        setVisible(false);
                        loginUI.setVisible(true);
                    }
                }
            }
            
            
            
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jbtn_RegisterActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        HomeUI_Login loginUI = new HomeUI_Login();
        setVisible(false);
        loginUI.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jtxt_EmployeeIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_EmployeeIDMouseEntered
       if(jtxt_EmployeeID.getText().contains("Employee ID")){
           jtxt_EmployeeID.setText("");
       }
    }//GEN-LAST:event_jtxt_EmployeeIDMouseEntered

    private void jtxt_EmployeeIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_EmployeeIDMouseExited
        if(jtxt_EmployeeID.getText().isEmpty()){
            jtxt_EmployeeID.setText("Employee ID");
        }
    }//GEN-LAST:event_jtxt_EmployeeIDMouseExited

    private void jtxt_EmpFirstNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_EmpFirstNameMouseEntered
        if(jtxt_EmpFirstName.getText().contains("First Name")){
            jtxt_EmpFirstName.setText("");
        }
    }//GEN-LAST:event_jtxt_EmpFirstNameMouseEntered

    private void jtxt_EmpFirstNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_EmpFirstNameMouseExited
        if(jtxt_EmpFirstName.getText().isEmpty()){
            jtxt_EmpFirstName.setText("First Name");
        }
    }//GEN-LAST:event_jtxt_EmpFirstNameMouseExited

    private void jtxt_EmpLastNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_EmpLastNameMouseEntered
        if(jtxt_EmpLastName.getText().contains("Last Name")){
            jtxt_EmpLastName.setText("");
        }
    }//GEN-LAST:event_jtxt_EmpLastNameMouseEntered

    private void jtxt_EmpLastNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxt_EmpLastNameMouseExited
        if(jtxt_EmpLastName.getText().isEmpty()){
            jtxt_EmpLastName.setText("Last Name");
        }
    }//GEN-LAST:event_jtxt_EmpLastNameMouseExited

    private void jpf_PasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpf_PasswordMouseEntered
        if(jpf_Password.getText().contains("Password")){
            jpf_Password.setText("");
        }
    }//GEN-LAST:event_jpf_PasswordMouseEntered

    private void jpf_PasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpf_PasswordMouseExited
        if(jpf_Password.getText().isEmpty()){
            jpf_Password.setEchoChar((char)0);
            jpf_Password.setText("Password");
           
        }
    }//GEN-LAST:event_jpf_PasswordMouseExited

    private void jpf_PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpf_PasswordKeyTyped
        jpf_Password.setEchoChar('*');
    }//GEN-LAST:event_jpf_PasswordKeyTyped

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            jpf_Password.setEchoChar((char)0);
        }
        else{
            jpf_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUI_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox_Branch;
    private javax.swing.JComboBox<String> jComboBox_Branch1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtn_Register;
    private javax.swing.JPasswordField jpf_Password;
    private javax.swing.JTextField jtxt_CustAddress;
    private javax.swing.JTextField jtxt_CustContactNumber;
    private javax.swing.JTextField jtxt_CustFirstName;
    private javax.swing.JTextField jtxt_CustLastName;
    private javax.swing.JTextField jtxt_EmpFirstName;
    private javax.swing.JTextField jtxt_EmpLastName;
    private javax.swing.JTextField jtxt_EmployeeID;
    // End of variables declaration//GEN-END:variables

    private void populateGUI(){
        try{
            ArrayList<Branch> list = branchDAO.getAllBranches();
            for(int i = 0;i<list.size();i++){
                jComboBox_Branch.addItem(list.get(i).getCity());
            }
            
            for(int i = 0;i<list.size();i++){
                jComboBox_Branch1.addItem(list.get(i).getCity());
            }
        }
        catch(Exception exc){
            exc.printStackTrace();
        }
    }
}
